name: Release
run-name: ${{ github.actor }} is running release
on:
  push:
    tag:
      - 'v\d+'

permissions:
  contents: read
  issues: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Define release variables
        id: release_variables
        run: |
          TAG=${{ github.ref_name }}
          DATETIME=$(git log -1 --format=%ai ${TAG})
          echo "tag_name=${TAG}" >> $GITHUB_OUTPUT
          echo "date_time=${DATETIME}" >> $GITHUB_OUTPUT

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.1.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          base-ref: 'origin/master'

      - name: Create issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.release_variables.outputs.tag_name }}
          AUTHOR: ${{ github.actor }}
          DATE: ${{ steps.release_variables.outputs.date_time }}
          BODY: ${{ steps.changelog.outputs.changelog }}
        with:
          update_existing: true
          search_existing: all
