name: Release
run-name: ${{ github.actor }} is running release
on:
  push:
    tag:
      - 'v\d+'

permissions:
  contents: read
  issues: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Define release variables
        id: release_variables
        run: |
          TAG=${{ github.ref_name }}
          DATETIME=$(git log -1 --format=%ai ${TAG})
          echo "tag_name=${TAG}" >> $GITHUB_OUTPUT
          echo "date_time=${DATETIME}" >> $GITHUB_OUTPUT

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.1.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          base-ref: master

      - name: Create issue
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          title: RELEASE ${{ steps.release_variables.outputs.tag_name }}
          body: |
            Release ${{ steps.release_variables.outputs.tag_name }}
            Author: ${{ github.actor }}
            Date: ${{ steps.release_variables.outputs.date_time }}
            ${{ steps.changelog.outputs.changelog }}
          labels: 'RELEASE'
