name: Release
run-name: ${{ github.actor }} is running release
on:
  push:
    tags:
      - 'v\d+'

permissions:
  contents: read
  issues: write
  pages: write
  id-token: write

jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Define release variables
        id: release_variables
        run: |
          TAG=${{ github.ref_name }}
          DATETIME=$(git log -1 --format=%ai ${TAG})
          PREV_TAG=$(git describe --tags --abbrev=0 ${TAG}^ || echo "origin/master")
          echo "tag_name=${TAG}" >> $GITHUB_OUTPUT
          echo "date_time=${DATETIME}" >> $GITHUB_OUTPUT
          echo "prev_tag_name=${PREV_TAG}" >> $GITHUB_OUTPUT

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.1.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          base-ref: ${{ steps.release_variables.outputs.prev_tag_name }}

      - name: Create issue
        id: create_issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.release_variables.outputs.tag_name }}
          AUTHOR: ${{ github.actor }}
          DATE: ${{ steps.release_variables.outputs.date_time }}
          BODY: ${{ steps.changelog.outputs.changelog }}
        with:
          update_existing: true
          search_existing: all
    outputs:
      number: ${{ steps.create_issue.outputs.number }}

  test:
    needs: [ issue ]
    uses: ./.github/workflows/ci.yml

  pre_deploy:
    needs: [ test, issue ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Comment issue after success testing
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue comment ${{ needs.issue.outputs.number }} \
          --body "Action ${{ github.run_id }}, Tests finished successfully"

  deploy:
    needs: [ pre_deploy ]
    uses: ./.github/workflows/deploy.yml

  post_deploy:
    needs: [ issue, deploy ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Comment issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue comment ${{ needs.issue.outputs.number }} \
          --body "Deploy ${{ github.run_id }}, link: https://neiloxx.github.io/unit-demo-cra/"
      - name: Close issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue close ${{ needs.issue.outputs.number }} -c "Issue closed automatically after successful Deploy"
