name: Release
run-name: ${{ github.actor }} is running release
on:
  push:
    tag:
      - 'v\d+'

permissions:
  contents: read
  issues: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create changelog text
        id: changelog
        uses: TriPSs/conventional-changelog-action@latest
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: 'false'
          git-push: 'false'
          version-path: ${{ github.ref_name }}

      - name: Create issue
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'RELEASE ${{ github.ref_name }}'
          body: ${{ steps.changelog.outputs.changelog }}
          labels: 'RELEASE'
