name: Release
run-name: ${{ github.actor }} is running release
on:
  push:
    tag:
      - 'v\d+'

permissions:
  contents: read
  issues: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: release_variables
        run: |
          TAG = ${{ github.ref_name }}
          echo "tag_name=$TAG" >> $GITHUB_OUTPUT
          echo "date_time=$(git log -1 --format=%ai $TAG)" >> $GITHUB_OUTPUT

      - name: Create changelog text
        id: changelog
        uses: TriPSs/conventional-changelog-action@latest
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: 'false'
          git-push: 'false'
          version-path: ${{ steps.release_variables.tag_name }}

      - name: Create issue
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          title: RELEASE ${{ steps.release_variables.tag_name }}
          body: |
            Release ${{ steps.release_variables.tag_name }}
            Author: ${{ github.actor }}
            Date: ${{ steps.release_variables.date_time }}
            ${{ steps.changelog.outputs.changelog }}
          labels: 'RELEASE'
